---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
  labels:
    app.kubernetes.io/component: net-certmanager
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-serving
    networking.knative.dev/certificate-provider: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: knative-internal-encryption-issuer
  labels:
    app.kubernetes.io/component: net-certmanager
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-serving
    networking.knative.dev/certificate-provider: cert-manager
spec:
  ca:
    secretName: knative-internal-encryption-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knative-internal-encryption-ca
  namespace: cert-manager #  If you want to use it as a ClusterIssuer the secret must be in the cert-manager namespace.
  labels:
    app.kubernetes.io/component: net-certmanager
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-serving
    networking.knative.dev/certificate-provider: cert-manager
spec:
  secretName: knative-internal-encryption-ca
  commonName: knative.dev
  usages:
    - server auth
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
